#!/usr/bin/env bash
# =============================================================================
# snes9x-manager.sh
# SNES9X Manager for Raspberry Pi 4
# Version: 2.2.3
# Last updated: 2026-06-10
#
# Self-contained — generates all required files on Install:
#   • snes9x-gtk   (compiled from source)  → ~/.local/bin/snes9x-gtk
#   • snes9x.conf  (pre-tuned for Pi 4)    → ~/.config/snes9x/snes9x.conf
#   • Desktop shortcut + icon              → ~/.local/share/
#
# snes9x — Portable Super Nintendo Entertainment System (TM) emulator
#   Source:    https://github.com/snes9xgit/snes9x
#   Compiling: https://github.com/snes9xgit/snes9x/wiki/Compiling
#   License:   Snes9x is freeware for PERSONAL USE only (non-commercial).
#              https://github.com/snes9xgit/snes9x/blob/master/LICENSE
#
# Features:
#   • Builds snes9x-gtk 1.63 from source with Pi 4 optimized flags
#     (-O3 -mcpu=cortex-a72), native Wayland EGL via +rpt Mesa
#   • PipeWire audio via PulseAudio shim — works alongside Cava/Shairport
#   • Writes a fully pre-tuned snes9x.conf at install — no manual setup
#   • Frame Skip = 0, vsync ON, OpenGL backend pre-set
#   • Direct snes9x-gtk desktop shortcut (no Python frontend)
#   • FRESH-COMPILE GUARANTEE — crash recovery via marker files
#   • Clean uninstall — never touches ROMs, retains apt dependencies
#
# Star Fox 2 / SuperFX2 note:
#   Pi 4 at 2.2 GHz locks 60 fps host rate on all SNES titles.
#   Star Fox 2 renders ~20 fps internally — correct hardware behaviour.
#
# Requirements:
#   - Raspberry Pi OS Trixie (Debian 13) arm64, labwc Wayland compositor
#   - PipeWire audio (default on Trixie)
#   - Internet connection for initial build
#   - ~400 MB free disk space during build (~250 MB freed afterwards)
#
# Usage:
#   chmod +x snes9x-manager.sh && ./snes9x-manager.sh
#
# Do NOT run as root. Only play games you legally own.
# =============================================================================

# =============================================================================
# AI DEVELOPER NOTES
# Hard-won lessons from building and debugging this script.
# Read this before making any changes.
# =============================================================================
#
# ── WAYLAND / OPENGL ─────────────────────────────────────────────────────────
#
# USE_WAYLAND=ON is CORRECT for Pi OS Trixie. Do NOT change to OFF.
#
# Pi OS ships Raspberry Pi Foundation Mesa builds with +rpt suffix:
#   libegl1-mesa-dev 25.0.7-2+rpt4  (from archive.raspberrypi.com)
#   libcairo2-dev    1.18.4-1+rpt1
# These are patched specifically for VideoCore VI EGL/Wayland. The native
# Wayland EGL path is FASTER and MORE STABLE than XWayland on this hardware.
#
# DO NOT add GDK_BACKEND=x11 to the Exec= line. It was tried and made
# performance worse and broke OpenGL rendering entirely. The crt-pi external
# GLSL shader also stopped working when XWayland was forced.
#
# ── EXTERNAL SHADERS (crt-pi) ────────────────────────────────────────────────
#
# The crt-pi GLSL shader was removed. Do NOT re-add it.
# It did not work reliably with this Wayland/EGL configuration.
# The built-in snes9x filters (hq2x, scanlines, etc.) work correctly and
# are accessible via snes9x → Preferences → Display.
#
# ── AUDIO / PIPEWIRE ─────────────────────────────────────────────────────────
#
# This script makes ZERO changes to PipeWire, WirePlumber, or ALSA config.
# PipeWire is the system audio stack on Pi OS Trixie and must never be
# replaced, restarted, or reconfigured by any script in this suite.
#
# snes9x audio chain:
#   snes9x (SoundDriver=1 PulseAudio client)
#     → PipeWire PulseAudio socket (/run/user/1000/pulse/native)
#     → PipeWire (routes to HDMI or Bluetooth)
#
# SoundDriver = 1 is PulseAudio. On Trixie this connects to PipeWire's
# compatibility shim. Cava, Shairport Sync, and Spotify are unaffected —
# PipeWire handles all routing and mixing transparently.
#
# portaudio19-dev is installed to satisfy snes9x 1.63's unconditional
# portaudio-2.0 pkg_check_modules at CMakeLists.txt line 186. There is no
# cmake flag to disable it in this release — installing the dev package is
# the only solution. portaudio19-dev is compile-time headers only; it does
# not install any runtime audio daemon or conflict with PipeWire.
#
# ── CONTROLLER PRESETS ───────────────────────────────────────────────────────
#
# Controller preset pre-writing was attempted and REMOVED. Do NOT re-add it.
# The GTK port uses SDL2 for joystick input. The conf key format for
# controller bindings is generated by snes9x's own GUI and depends on SDL2's
# device enumeration order — it cannot be reliably pre-written by a script.
# Users must configure controllers in snes9x → Preferences → Joypads.
#
# ── BUILD FLAGS ──────────────────────────────────────────────────────────────
#
# PI4_CFLAGS="-O3 -mcpu=cortex-a72" is correct for Pi 4 (Cortex-A72 cores).
# DO NOT add -DUSE_OPENGL=ON — this flag does not exist in snes9x 1.63's
# CMakeLists.txt and generates a cmake warning about unused variables.
#
# USE_SLANG=OFF skips compiling glslang and SPIRV-Cross (Vulkan shader
# compilers). These are not needed on Pi 4 — slang shaders require Vulkan
# which VideoCore VI does not support. Leaving OFF cuts compile time
# significantly and removes the most fragile part of the build.
#
# ── SNES9X 1.63 vs MASTER ────────────────────────────────────────────────────
#
# Pinned to tag 1.63 (Jul 2024). No Pi 4-specific improvements have been
# documented in master since this tag. 1.63 is thoroughly tested on
# Pi OS Trixie/labwc. Master is a moving target; stay on 1.63 unless a
# specific game bug in master is confirmed to fix a real issue.
#
# ── STAR FOX 2 / SUPERFX2 PERFORMANCE ───────────────────────────────────────
#
# Star Fox 2 runs at ~20 fps in-game. This is CORRECT behaviour — the
# SuperFX2 chip in the real cartridge only renders ~20 fps. The snes9x host
# runs at 60 fps. Frame Skip must be 0; Pi 4 @ 2.2 GHz has no trouble.
# Do not attempt to "fix" the 20 fps — it is hardware-accurate emulation.
#
# =============================================================================

set -euo pipefail

# ── Build directory trap ──────────────────────────────────────────────────────
# Tracks the active /tmp build dir so it gets cleaned on unexpected exit
# (compile error, OOM, Ctrl+C, etc.). Prevents /tmp fill-up on Pi 4.
_ACTIVE_BUILD_DIR=""
_cleanup_build_trap() {
    if [[ -n "$_ACTIVE_BUILD_DIR" && -d "$_ACTIVE_BUILD_DIR" \
          && "$_ACTIVE_BUILD_DIR" == /tmp/* ]]; then
        rm -rf "$_ACTIVE_BUILD_DIR"
    fi
}
trap _cleanup_build_trap EXIT

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'
BOLD='\033[1m'; NC='\033[0m'
info()       { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()       { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()      { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }
step()       { echo -e "\n${CYAN}── $* ──${NC}"; }
divider()    { echo -e "${CYAN}════════════════════════════════════════════════════════════${NC}"; }
print_ok()   { echo -e "  ${GREEN}✔${NC}  $*"; }
print_info() { echo -e "  ${CYAN}•${NC}  $*"; }

# ── Paths ─────────────────────────────────────────────────────────────────────
INSTALL_BIN="$HOME/.local/bin"
SNES9X_BIN="$INSTALL_BIN/snes9x-gtk"
CONFIG_DIR="$HOME/.config/snes9x"
SNES9X_CONF="$CONFIG_DIR/snes9x.conf"
ROM_DIR="$HOME/ROMs/snes"
DESKTOP_DIR="$HOME/.local/share/applications"
DESKTOP_FILE="$DESKTOP_DIR/snes9x-gtk.desktop"   # snes9x emulator shortcut
MANAGER_DESKTOP_FILE="$DESKTOP_DIR/snes9x-manager.desktop" # this manager script

# Crash-recovery state markers
STATE_DIR="$CONFIG_DIR/.snes9x-manager"
PARTIAL_MARKER="$STATE_DIR/partial-install"
BUILD_DIR_FILE="$STATE_DIR/build-dir"

# ── Source & build config ─────────────────────────────────────────────────────
SNES9X_REPO="https://github.com/snes9xgit/snes9x.git"
SNES9X_TAG="1.63"
# Ref: https://gcc.gnu.org/onlinedocs/gcc/AArch64-Options.html
PI4_CFLAGS="-O3 -mcpu=cortex-a72"

[[ "$EUID" -eq 0 ]] && error "Do not run this script as root."

# =============================================================================
# STATUS DISPLAY
# =============================================================================
snes9x_status() {
    if [[ -x "$SNES9X_BIN" ]]; then
        print_ok "snes9x-gtk installed: $SNES9X_BIN  (tag $SNES9X_TAG)"
    else
        print_info "snes9x-gtk: not installed"
    fi
    if [[ -f "$DESKTOP_FILE" ]]; then
        print_ok "Desktop shortcut present"
    else
        print_info "Desktop shortcut: not installed"
    fi
    if [[ -f "$SNES9X_CONF" ]]; then
        print_ok "snes9x.conf present"
        # Show frameskip so user can quickly verify it's 0
        local fs
        fs=$(grep -E '^\s*FrameSkip' "$SNES9X_CONF" 2>/dev/null | head -2 || true)
        if [[ -n "$fs" ]]; then
            print_info "Frameskip: $(echo "$fs" | tr '\n' ' ')"
        else
            print_info "Frameskip: key not written yet (launch snes9x once)"
        fi
    else
        print_info "snes9x.conf: not installed"
    fi
    local count=0
    if [[ -d "$ROM_DIR" ]]; then
        count=$(find "$ROM_DIR" -maxdepth 4 -type f \
            \( -iname '*.sfc' -o -iname '*.smc' -o -iname '*.fig' -o -iname '*.zip' \) \
            2>/dev/null | wc -l)
        print_info "ROM folder: $ROM_DIR  ($count file(s))"
    else
        print_info "ROM folder: $ROM_DIR  (will be created on install)"
    fi
}

# =============================================================================
# CRASH-RECOVERY MACHINERY
# _begin_build / _end_build bracket the compile. If the script is killed
# mid-build, PARTIAL_MARKER survives. The next Install/Update detects it,
# removes the stale /tmp build dir, wipes installed files, and starts clean.
# =============================================================================
_begin_build() {
    mkdir -p "$STATE_DIR"
    date '+%Y-%m-%d %H:%M:%S' > "$PARTIAL_MARKER"
    echo "$1" > "$BUILD_DIR_FILE"
    _ACTIVE_BUILD_DIR="$1"   # expose to EXIT trap
}

_end_build() {
    rm -f "$PARTIAL_MARKER" "$BUILD_DIR_FILE"
    _ACTIVE_BUILD_DIR=""   # disarm the EXIT trap
}

_remove_stale_build_dir() {
    if [[ -f "$BUILD_DIR_FILE" ]]; then
        local stale_dir
        stale_dir=$(cat "$BUILD_DIR_FILE")
        if [[ -n "$stale_dir" && -d "$stale_dir" && "$stale_dir" == /tmp/* ]]; then
            rm -rf "$stale_dir"
            info "Removed stale build directory: $stale_dir"
        fi
        rm -f "$BUILD_DIR_FILE"
    fi
}

_check_partial_state() {
    if [[ -f "$PARTIAL_MARKER" ]]; then
        echo ""
        warn "A previous Install/Update did not finish (started: $(cat "$PARTIAL_MARKER"))."
        info "No problem — the next Install/Update automatically cleans up and starts fresh."
        echo ""
    fi
}

# Removes every file this script places on the system. Called by both
# _fresh_clean (before every build) and do_uninstall.
_remove_installed_files() {
    [[ -f "$SNES9X_BIN" ]]   && rm -f "$SNES9X_BIN"   && info "Removed: $SNES9X_BIN"
    [[ -f "$DESKTOP_FILE" ]]         && rm -f "$DESKTOP_FILE"         && info "Removed: $DESKTOP_FILE"
    [[ -f "$MANAGER_DESKTOP_FILE" ]] && rm -f "$MANAGER_DESKTOP_FILE" && info "Removed: $MANAGER_DESKTOP_FILE"

    # Remove anything snes9x's own cmake --install placed under ~/.local
    for f in \
        "$DESKTOP_DIR/snes9x-gtk.desktop" \
        "$DESKTOP_DIR/snes9x.desktop"; do
        [[ -f "$f" ]] && rm -f "$f" && info "Removed: $f"
    done
    if [[ -d "$HOME/.local/share/icons" ]]; then
        while IFS= read -r -d '' f; do
            rm -f "$f" && info "Removed icon: $f"
        done < <(find "$HOME/.local/share/icons" -name 'snes9x*' -type f -print0 2>/dev/null)
    fi
    for f in \
        "$HOME/.local/share/metainfo/snes9x-gtk.appdata.xml" \
        "$HOME/.local/share/metainfo/snes9x-gtk.metainfo.xml" \
        "$HOME/.local/share/appdata/snes9x-gtk.appdata.xml"; do
        [[ -f "$f" ]] && rm -f "$f" && info "Removed: $f"
    done
    [[ -d "$HOME/.local/share/snes9x" ]] && \
        rm -rf "$HOME/.local/share/snes9x" && info "Removed: $HOME/.local/share/snes9x"
    if [[ -d "$HOME/.local/share/locale" ]]; then
        while IFS= read -r -d '' f; do
            rm -f "$f" && info "Removed locale: $f"
        done < <(find "$HOME/.local/share/locale" -name 'snes9x*.mo' -type f -print0 2>/dev/null)
    fi

    update-desktop-database "$DESKTOP_DIR" 2>/dev/null || true
    gtk-update-icon-cache -f -t "$HOME/.local/share/icons/hicolor" 2>/dev/null || true
}

_fresh_clean() {
    step "Fresh-compile clean"
    _remove_stale_build_dir
    _remove_installed_files
    print_ok "Clean slate ready."
}

# =============================================================================
# PRE-TUNED snes9x.conf WRITER
#
# Written at install time — snes9x will read and use it on first launch.
# All Pi 4 performance settings baked in.
#
# Key decisions documented inline:
#   • OpenGL output — VideoCore VI GPU via native Wayland EGL (+rpt Mesa)
#   • FrameSkip = 0 — Pi 4 @ 2.2 GHz never needs to skip frames
#   • SoundDriver = 1 (PulseAudio) — uses PipeWire's PA shim on Trixie
#   • Vsync ON — smooth 60 fps pacing with labwc compositor
#
# Ref: snes9x.conf format confirmed from community configs:
#   https://www.snes9x.com/phpbb3/viewtopic.php?t=22048
#   https://www.emulator-zone.com/showthread.php?t=26296
# =============================================================================
write_snes9x_conf() {
    mkdir -p "$CONFIG_DIR"
    # Back up any existing conf the user may have edited
    if [[ -f "$SNES9X_CONF" ]]; then
        cp "$SNES9X_CONF" "${SNES9X_CONF}.bak"
        info "Existing snes9x.conf backed up to ${SNES9X_CONF}.bak"
    fi
    cat > "$SNES9X_CONF" << CONFEOF
# snes9x.conf — pre-tuned for Raspberry Pi 4 @ 2.2 GHz, Pi OS Trixie
# Generated by snes9x-manager.sh. Re-run Install to regenerate.
# Ref: https://github.com/snes9xgit/snes9x

[Display]
# OpenGL output — VideoCore VI GPU via native Wayland EGL.
# Pi OS Trixie ships +rpt Mesa packages optimised for VideoCore VI.
VideoMode = 2

# Bilinear filter OFF — raw sharp pixels.
# Enable in snes9x → Preferences → Display if you prefer a softer look.
BilinearFilter = 0

# Sync to vertical blank — essential for smooth 60 fps on labwc (60 Hz).
# Without vsync, frames tear and pacing becomes irregular.
VSync = 1

# Aspect ratio: maintain 4:3 SNES native ratio at all output sizes.
MaintainAspectRatio = 1

# Reduce input lag — ON by default. Trades one frame of GPU buffering for
# lower controller latency. Disable here if you see stutter.
ReduceInputLag = 1

[Sound]
# PulseAudio driver — PipeWire on Trixie exposes a PulseAudio socket.
# Shairport Sync, Spotify, and Cava all continue working as normal.
# Ref: https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/FAQ
SoundDriver = 1

# 64 ms buffer — lowest latency that reliably avoids crackle on Pi 4.
# Raise to 96 ms only if you hear audio dropouts.
SoundBufferSize = 64

# Dynamic rate control — adjusts audio clock slightly to eliminate
# buffer underruns without introducing noticeable pitch shift.
DynamicRateControl = 1

[Emulation]
# Frame Skip = 0 — Pi 4 at 2.2 GHz handles every SNES title at full speed.
# Star Fox 2's ~20 fps is the SuperFX2 chip's hardware rate, not a perf issue.
# NEVER enable frameskip on this hardware.
FrameSkipType = 0
FrameSkipValue = 0

CONFEOF
    info "snes9x.conf written: $SNES9X_CONF"
}

# =============================================================================
# DESKTOP SHORTCUTS
#
# Two shortcuts are written:
#
#   1. snes9x-gtk.desktop  — launches snes9x-gtk directly (the emulator)
#      cmake --install writes this; we overwrite Exec= with the absolute
#      path so it works regardless of whether ~/.local/bin is in $PATH.
#      Uses snes9x's own installed icons (16px–256px + scalable) and
#      MimeType= so the file manager offers "Open with Snes9x" for ROMs.
#
#   2. snes9x-manager.desktop — launches this manager script in a terminal
#      Separate entry so the two are clearly distinct in the app launcher.
# =============================================================================
write_desktop_shortcuts() {
    mkdir -p "$DESKTOP_DIR"

    # ── 1. Snes9x emulator shortcut ───────────────────────────────────────────
    # Always write fresh — guarantees Exec= is the full absolute path.
    # Runs natively under Wayland via labwc — Pi OS +rpt Mesa packages make
    # the EGL/Wayland path the correct choice on VideoCore VI.
    # Uses Icon=snes9x which matches the icon names cmake --install places
    # in hicolor (snes9x.png / snes9x.svg).
    cat > "$DESKTOP_FILE" << EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=Snes9x
GenericName=SNES Emulator
Comment=Super Nintendo Entertainment System emulator — Pi 4 optimized build
Exec=$SNES9X_BIN %f
Icon=snes9x
Terminal=false
Categories=Game;Emulator;
Keywords=snes;nintendo;emulator;retro;
MimeType=application/x-snes-rom;
StartupWMClass=snes9x-gtk
StartupNotify=true
EOF
    chmod 644 "$DESKTOP_FILE"
    info "Emulator shortcut written: $DESKTOP_FILE"

    # ── 2. Manager script shortcut ────────────────────────────────────────────
    # Resolves to the script's own location at install time.
    local SCRIPT_PATH
    SCRIPT_PATH="$(realpath "${BASH_SOURCE[0]}")"
    cat > "$MANAGER_DESKTOP_FILE" << EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=Snes9x Manager
GenericName=SNES Emulator Manager
Comment=Install, update, and configure snes9x — Pi 4 manager script
Exec=foot -- bash "$SCRIPT_PATH"
Icon=snes9x
Terminal=false
Categories=Game;Emulator;System;
Keywords=snes;nintendo;emulator;manager;install;
StartupNotify=false
EOF
    chmod 644 "$MANAGER_DESKTOP_FILE"
    info "Manager shortcut written: $MANAGER_DESKTOP_FILE"

    gtk-update-icon-cache -f -t "$HOME/.local/share/icons/hicolor" 2>/dev/null || true
    update-desktop-database "$DESKTOP_DIR" 2>/dev/null || true
}

# =============================================================================
# INSTALL
# =============================================================================
do_install() {
    step "Installing build dependencies"
    # libportaudio-dev: snes9x 1.63's CMakeLists.txt checks for portaudio-2.0
    # at line 186 with REQUIRED and no cmake flag to disable it.
    # Installing portaudio19-dev (the Debian package name) satisfies the check.
    # PipeWire on Trixie remains the active audio system — portaudio is just a
    # compiled-in driver that snes9x won't use (PulseAudio/PipeWire is chosen).
    # Ref: https://github.com/snes9xgit/snes9x/blob/1.63/gtk/CMakeLists.txt
    sudo apt-get update
    sudo apt-get install -y \
        build-essential \
        cmake \
        git \
        pkg-config \
        curl \
        libgtkmm-3.0-dev \
        libsdl2-dev \
        libx11-dev \
        libxext-dev \
        libxv-dev \
        libxrandr-dev \
        libwayland-dev \
        wayland-protocols \
        libepoxy-dev \
        libpulse-dev \
        libasound2-dev \
        portaudio19-dev \
        libminizip-dev \
        zlib1g-dev \
        libpng-dev \
        gettext
    info "Build dependencies ready."

    _fresh_clean

    step "Building snes9x-gtk $SNES9X_TAG"
    local BUILD_DIR
    BUILD_DIR="$(mktemp -d /tmp/snes9x-build.XXXXXX)"
    _begin_build "$BUILD_DIR"
    cd "$BUILD_DIR" || error "Failed to enter build directory"

    # Clone with retry — shallow clone + submodules for minimal download size.
    # --shallow-submodules avoids full history of SPIRV-Cross/glslang (~100 MB saved).
    local GIT_RETRY=0
    until git clone --depth=1 --branch "$SNES9X_TAG" \
        --recurse-submodules --shallow-submodules \
        "$SNES9X_REPO" 2>&1; do
        GIT_RETRY=$((GIT_RETRY + 1))
        [[ $GIT_RETRY -ge 3 ]] && error "Git clone failed after 3 retries. Check network."
        warn "Git clone failed (attempt $GIT_RETRY) — retrying in $((GIT_RETRY * 5))s…"
        sleep $((GIT_RETRY * 5))
    done
    cd snes9x/gtk || error "snes9x/gtk directory missing after clone"
    info "Cloned tag: $SNES9X_TAG"

    # CMake configure.
    # USE_WAYLAND=ON  — native Wayland EGL surface for labwc (Trixie default).
    #   Pi OS Trixie ships Raspberry Pi Foundation Mesa builds (+rpt packages)
    #   which are specifically optimised for VideoCore VI EGL/Wayland.
    #   These are MORE performant than XWayland on this hardware.
    #   Ref: archive.raspberrypi.com libegl1-mesa-dev 25.0.7-2+rpt4
    # USE_PULSEAUDIO=ON — PipeWire's PulseAudio shim (primary audio path)
    # USE_SLANG=OFF   — skip glslang/SPIRV-Cross compile; not needed on Pi 4
    # portaudio19-dev satisfies the unconditional portaudio-2.0 pkg check
    # Refs: https://github.com/snes9xgit/snes9x/wiki/Compiling
    #       https://gcc.gnu.org/onlinedocs/gcc/AArch64-Options.html
    cmake -B build \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX="$HOME/.local" \
        -DUSE_WAYLAND=ON \
        -DUSE_PULSEAUDIO=ON \
        -DUSE_SLANG=OFF \
        -DCMAKE_C_FLAGS="$PI4_CFLAGS" \
        -DCMAKE_CXX_FLAGS="$PI4_CFLAGS"

    cmake --build build -j"$(nproc)"

    if ! cmake --install build; then
        warn "cmake --install reported an issue — falling back to direct binary copy."
        mkdir -p "$INSTALL_BIN"
        install -Dm755 build/snes9x-gtk "$SNES9X_BIN"
    fi
    [[ -x "$SNES9X_BIN" ]] || error "Build completed but $SNES9X_BIN not found."
    info "snes9x-gtk installed: $SNES9X_BIN"

    step "Writing pre-tuned snes9x.conf"
    write_snes9x_conf

    step "Creating ROM folder"
    mkdir -p "$ROM_DIR"
    info "ROM folder ready: $ROM_DIR"

    step "Writing desktop shortcut"
    write_desktop_shortcuts

    cd "$HOME"
    _end_build
    rm -rf "$BUILD_DIR" 2>/dev/null || true

    echo ""
    divider
    echo -e "${GREEN}  Install complete!${NC}"
    divider
    print_info "Drop .sfc / .smc / .zip ROMs into: $ROM_DIR"
    print_info "Launch snes9x from the application menu or run: $SNES9X_BIN"
    print_info "Audio: PipeWire/PulseAudio pre-set — works with Cava and Shairport"
    print_info "Controllers: Preferences → Joypads tab"
    echo ""
}

# =============================================================================
# UPDATE — identical build process to Install, conf preserved (not overwritten)
# =============================================================================
do_update() {
    if [[ ! -x "$SNES9X_BIN" ]]; then
        warn "snes9x is not installed. Run Install first."
        return 0
    fi
    echo ""
    echo "  1) Rebuild pinned stable tag ($SNES9X_TAG)  — recommended"
    echo "  2) Build latest master (newest fixes, may change daily)"
    echo ""
    read -rp "$(echo -e "${CYAN}  Choose [1-2]: ${NC}")" UPD || true
    local CLONE_ARGS=(--depth=1 --recurse-submodules --shallow-submodules)
    case "${UPD:-1}" in
        2) info "Building latest master." ;;
        *) CLONE_ARGS+=(--branch "$SNES9X_TAG"); info "Rebuilding tag $SNES9X_TAG." ;;
    esac

    _fresh_clean

    step "Building snes9x-gtk"
    local BUILD_DIR
    BUILD_DIR="$(mktemp -d /tmp/snes9x-build.XXXXXX)"
    _begin_build "$BUILD_DIR"
    cd "$BUILD_DIR" || error "Failed to enter build directory"

    local GIT_RETRY=0
    until git clone "${CLONE_ARGS[@]}" "$SNES9X_REPO" 2>&1; do
        GIT_RETRY=$((GIT_RETRY + 1))
        [[ $GIT_RETRY -ge 3 ]] && error "Git clone failed after 3 retries."
        warn "Git clone failed (attempt $GIT_RETRY) — retrying in $((GIT_RETRY * 5))s…"
        sleep $((GIT_RETRY * 5))
    done
    cd snes9x/gtk || error "snes9x/gtk directory missing after clone"

    cmake -B build \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX="$HOME/.local" \
        -DUSE_WAYLAND=ON \
        -DUSE_PULSEAUDIO=ON \
        -DUSE_SLANG=OFF \
        -DCMAKE_C_FLAGS="$PI4_CFLAGS" \
        -DCMAKE_CXX_FLAGS="$PI4_CFLAGS"

    cmake --build build -j"$(nproc)"

    if ! cmake --install build; then
        warn "cmake --install fallback — direct copy."
        install -Dm755 build/snes9x-gtk "$SNES9X_BIN"
    fi
    [[ -x "$SNES9X_BIN" ]] || error "Build completed but binary not found."

    step "Reinstalling desktop shortcut"
    write_desktop_shortcuts

    cd "$HOME"
    _end_build
    rm -rf "$BUILD_DIR" 2>/dev/null || true

    echo ""
    print_ok "Update complete. Your snes9x.conf, saves, and ROMs are unchanged."
    echo ""
}

# =============================================================================
# PERFORMANCE GUIDE
# =============================================================================
performance_guide() {
    echo ""
    divider
    echo -e "${BOLD}  Performance & display guide — Pi 4 @ 2.2 GHz${NC}"
    divider
    echo ""
    echo "  Everything below is pre-set in snes9x.conf. This is for reference."
    echo ""
    echo "  Frame Skip:"
    print_info "FrameSkipType = 0  (no skip — Pi 4 never needs it)"
    print_info "Star Fox 2 at ~20 fps in-game is correct SuperFX2 hardware behaviour."
    print_info "The host emulator still runs at 60 fps — that is your stability."
    echo ""
    echo "  Display:"
    print_info "OpenGL output via native Wayland EGL (labwc compositor)"
    print_info "Pi OS +rpt Mesa — VideoCore VI EGL is faster than XWayland"
    print_info "Vsync ON — smooth 60 Hz pacing with labwc"
    echo ""
    echo "  Audio:"
    print_info "PipeWire via PulseAudio shim — SoundDriver = 1 (pre-set in snes9x.conf)"
    print_info "64 ms buffer — raise to 96 ms if you hear crackle"
    print_info "Dynamic rate control ON — eliminates buffer underruns"
    print_info "Shairport Sync, Cava, Spotify unaffected — PipeWire handles routing"
    echo ""
    echo "  References:"
    print_info "https://github.com/snes9xgit/snes9x/wiki"
    print_info "https://pipewire.org"
    echo ""
}

# =============================================================================
# UNINSTALL
# =============================================================================
do_uninstall() {
    step "Uninstalling snes9x"
    _remove_stale_build_dir
    rm -f "$PARTIAL_MARKER"
    _remove_installed_files
    [[ -d "$STATE_DIR" ]] && rm -rf "$STATE_DIR" && info "Removed: $STATE_DIR"

    # ── Config file (snes9x.conf) ─────────────────────────────────────────────
    # This is just preferences — display mode, audio driver, input bindings.
    # Safe to delete; snes9x regenerates it on next launch.
    echo ""
    if [[ -f "$SNES9X_CONF" ]]; then
        echo "  Config file: $SNES9X_CONF"
        echo "  Contains: display/audio/input preferences. Regenerated automatically."
        read -rp "$(echo -e "${CYAN}  Remove snes9x.conf (settings only)? [y/N]: ${NC}")" RM_CONF || true
        if [[ "$RM_CONF" =~ ^[Yy]$ ]]; then
            rm -f "$SNES9X_CONF" "${SNES9X_CONF}.bak"
            info "Config file removed."
        else
            info "Config kept: $SNES9X_CONF"
        fi
    else
        print_info "No snes9x.conf found — nothing to remove."
    fi

    # ── Battery saves (.srm files) ────────────────────────────────────────────
    # These are your in-game progress — IRREPLACEABLE. Default: keep.
    echo ""
    local SRM_COUNT=0
    SRM_COUNT=$(find "$CONFIG_DIR" -maxdepth 2 -name '*.srm' 2>/dev/null | wc -l)
    if [[ $SRM_COUNT -gt 0 ]]; then
        echo "  Battery saves (.srm): $SRM_COUNT file(s) found in $CONFIG_DIR"
        warn "These contain your in-game progress and CANNOT be recovered if deleted."
        read -rp "$(echo -e "${CYAN}  Remove battery saves (.srm)? [y/N]: ${NC}")" RM_SRM || true
        if [[ "$RM_SRM" =~ ^[Yy]$ ]]; then
            find "$CONFIG_DIR" -maxdepth 2 -name '*.srm' -delete
            info "Battery saves removed."
        else
            info "Battery saves kept."
        fi
    else
        print_info "No battery saves (.srm) found."
    fi

    # ── Save states ────────────────────────────────────────────────────────────
    # These are snapshot saves (not in-game saves). Default: keep.
    echo ""
    local STATE_COUNT=0
    STATE_COUNT=$(find "$CONFIG_DIR" -maxdepth 2         \( -name '*.sst' -o -name '*.oops' -o -name '*.undo'            -o -name '*.000' -o -name '*.001' -o -name '*.002'            -o -name '*.003' -o -name '*.004' -o -name '*.005'            -o -name '*.006' -o -name '*.007' -o -name '*.008'            -o -name '*.009' \) 2>/dev/null | wc -l)
    if [[ $STATE_COUNT -gt 0 ]]; then
        echo "  Save states: $STATE_COUNT file(s) found in $CONFIG_DIR"
        read -rp "$(echo -e "${CYAN}  Remove save states? [y/N]: ${NC}")" RM_STATES || true
        if [[ "$RM_STATES" =~ ^[Yy]$ ]]; then
            find "$CONFIG_DIR" -maxdepth 2                 \( -name '*.sst' -o -name '*.oops' -o -name '*.undo'                    -o -name '*.000' -o -name '*.001' -o -name '*.002'                    -o -name '*.003' -o -name '*.004' -o -name '*.005'                    -o -name '*.006' -o -name '*.007' -o -name '*.008'                    -o -name '*.009' \) -delete 2>/dev/null || true
            info "Save states removed."
        else
            info "Save states kept."
        fi
    else
        print_info "No save states found."
    fi

    # ── Remove config directory if now empty ──────────────────────────────────
    if [[ -d "$CONFIG_DIR" ]]; then
        local REMAINING
        REMAINING=$(find "$CONFIG_DIR" -not -path "$STATE_DIR*"             -not -name '.*' -mindepth 1 2>/dev/null | wc -l)
        if [[ $REMAINING -eq 0 ]]; then
            rm -rf "$CONFIG_DIR"
            info "Config directory empty — removed: $CONFIG_DIR"
        else
            print_info "Config directory kept (contains files): $CONFIG_DIR"
        fi
    fi

    echo ""
    [[ -d "$ROM_DIR" ]] && print_info "Your ROMs are untouched: $ROM_DIR"

    # Build + runtime deps are retained — other system packages may depend on them.
    # To remove manually later:
    #   sudo apt-get remove build-essential cmake libgtkmm-3.0-dev libsdl2-dev \
    #       libx11-dev libxext-dev libxv-dev libxrandr-dev libwayland-dev \
    #       wayland-protocols libepoxy-dev libpulse-dev libasound2-dev \
    #       portaudio19-dev libminizip-dev zlib1g-dev libpng-dev gettext
    info "Dependencies retained (safe to leave; remove manually if needed)."

    echo ""
    divider
    echo -e "${GREEN}  snes9x fully uninstalled.${NC}"
    divider
    echo ""
    exit 0
}

# =============================================================================
# MAIN MENU
# =============================================================================
main_menu() {
    mkdir -p "$STATE_DIR"
    _check_partial_state

    while true; do
        echo ""
        divider
        echo -e "${BOLD}  SNES9X Manager — Raspberry Pi 4${NC}"
        echo -e "  snes9x-gtk ${SNES9X_TAG} | Pi OS Trixie arm64 | Wayland + OpenGL + PipeWire"
        echo -e "  Source: https://github.com/snes9xgit/snes9x"
        divider
        echo ""
        snes9x_status
        echo ""
        echo -e "  ${CYAN}1)${NC}  Install"
        echo -e "  ${CYAN}2)${NC}  Update  (fresh rebuild — stable tag or master)"
        echo -e "  ${CYAN}3)${NC}  Performance & display guide"
        echo -e "  ${CYAN}4)${NC}  Diagnostics"
        echo -e "  ${CYAN}5)${NC}  Edit snes9x.conf manually"
        echo -e "  ${CYAN}6)${NC}  Uninstall  (keeps dependencies, saves prompt, ROMs safe)"
        echo -e "  ${CYAN}7)${NC}  Exit"
        echo ""
        read -rp "$(echo -e "${CYAN}  Choose an option [1-7]: ${NC}")" CHOICE || true

        case "$CHOICE" in
            1) do_install ;;
            2) do_update  ;;
            3) performance_guide ;;
            4)
                echo ""
                divider
                echo -e "${BOLD}  Diagnostics${NC}"
                divider
                echo ""
                if [[ ! -f "$SNES9X_CONF" ]]; then
                    warn "snes9x.conf not found — run Install first."
                else
                    print_ok "snes9x.conf found at: $SNES9X_CONF"
                    echo ""
                    print_info "Frame Skip:"
                    grep -E '^\s*FrameSkip' "$SNES9X_CONF" 2>/dev/null \
                        | sed 's/^/    /' || echo "    (keys not yet written — launch snes9x once)"
                    echo ""
                    print_info "Audio driver (1=PulseAudio/PipeWire):"
                    grep -E '^\s*SoundDriver' "$SNES9X_CONF" 2>/dev/null \
                        | sed 's/^/    /' || echo "    (not configured)"
                    echo ""
                    print_info "Controller blocks:"
                    grep -E '^\s*Joypad[0-9]' "$SNES9X_CONF" 2>/dev/null \
                        | head -20 | sed 's/^/    /' || echo "    (none configured)"
                fi
                echo ""
                read -rp "$(echo -e "${CYAN}  Press Enter to continue… ${NC}")" _ || true
                ;;
            5)
                if [[ -f "$SNES9X_CONF" ]]; then
                    "${EDITOR:-nano}" "$SNES9X_CONF" 2>/dev/null || \
                        nano "$SNES9X_CONF" 2>/dev/null || \
                        vi   "$SNES9X_CONF"
                else
                    warn "snes9x.conf not found — run Install first."
                fi
                ;;
            6) do_uninstall ;;
            7)
                echo ""
                echo "  Goodbye. Enjoy Star Fox 2."
                echo ""
                exit 0
                ;;
            *) warn "Invalid choice — enter 1–7." ;;
        esac
    done
}

main_menu
